name: SnapSieve
options:
  bundleIdPrefix: com.marlowsousa.snapsieve
  deploymentTarget:
    macOS: "14.0"
    iOS: "17.0"
    visionOS: "1.0"
  xcodeVersion: "15.0"
  groupSortPosition: top
  generateEmptyDirectories: true
  defaultConfig: Debug

configs:
  Debug:
    settings:
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
  Release:
    settings:
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
      SWIFT_COMPILATION_MODE: wholemodule

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic

# Shared sources for all platforms
fileGroups:
  - Shared

targets:
  # ============================================
  # macOS App Target
  # ============================================
  SnapSieve:
    type: application
    platform: macOS
    sources:
      - path: PhotoCleaner
        excludes:
          - "**/*Tests*"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.marlowsousa.snapsieve
        INFOPLIST_FILE: PhotoCleaner/Info.plist
        CODE_SIGN_ENTITLEMENTS: PhotoCleaner/SnapSieve.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        LD_RUNPATH_SEARCH_PATHS:
          - "@executable_path/../Frameworks"
    info:
      path: PhotoCleaner/Info.plist
      properties:
        CFBundleName: Snap Sieve
        CFBundleDisplayName: Snap Sieve
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        LSMinimumSystemVersion: $(MACOSX_DEPLOYMENT_TARGET)
        NSPhotoLibraryUsageDescription: "Snap Sieve needs access to analyze and identify duplicates. All processing is local."
        NSPhotoLibraryAddUsageDescription: "Snap Sieve needs permission to manage and delete photos."
        LSApplicationCategoryType: public.app-category.photography
    entitlements:
      path: PhotoCleaner/SnapSieve.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.files.user-selected.read-write: true
        com.apple.security.assets.pictures.read-write: true
        com.apple.security.personal-information.photos-library: true
    scheme:
      testTargets:
        - SnapSieveTests
      gatherCoverageData: true

  # ============================================
  # macOS Tests Target
  # ============================================
  SnapSieveTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: PhotoCleanerTests
    dependencies:
      - target: SnapSieve
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.marlowsousa.snapsieve.tests
        INFOPLIST_FILE: PhotoCleanerTests/Info.plist
        TEST_HOST: $(BUILT_PRODUCTS_DIR)/SnapSieve.app/Contents/MacOS/SnapSieve
        BUNDLE_LOADER: $(TEST_HOST)

  # ============================================
  # iOS App Target
  # ============================================
  SnapSieveiOS:
    type: application
    platform: iOS
    sources:
      # iOS-specific sources
      - path: SnapSieveiOS
      # Shared Core sources (algorithms, models, data)
      - path: PhotoCleaner/Core/Algorithms
        group: Shared/Core/Algorithms
      - path: PhotoCleaner/Core/Models
        group: Shared/Core/Models
      - path: PhotoCleaner/Core/ML
        group: Shared/Core/ML
      - path: PhotoCleaner/Core/Utilities
        group: Shared/Core/Utilities
      # Shared services (except PhotoLibraryService which is platform-specific)
      - path: PhotoCleaner/Core/Services/ImageAnalysisService.swift
        group: Shared/Core/Services
      - path: PhotoCleaner/Core/Services/DuplicateDetectionService.swift
        group: Shared/Core/Services
      - path: PhotoCleaner/Core/Services/SimilarityGroupingService.swift
        group: Shared/Core/Services
      - path: PhotoCleaner/Core/Services/QualityAssessmentService.swift
        group: Shared/Core/Services
      - path: PhotoCleaner/Core/Services/BatchProcessingService.swift
        group: Shared/Core/Services
      - path: PhotoCleaner/Core/Services/CLIPEmbeddingService.swift
        group: Shared/Core/Services
      # Shared Data layer
      - path: PhotoCleaner/Data
        group: Shared/Data
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.marlowsousa.snapsieve.ios
        INFOPLIST_FILE: SnapSieveiOS/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
        LD_RUNPATH_SEARCH_PATHS:
          - "@executable_path/Frameworks"
    info:
      path: SnapSieveiOS/Info.plist
      properties:
        CFBundleName: Snap Sieve
        CFBundleDisplayName: Snap Sieve
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        MinimumOSVersion: $(IPHONEOS_DEPLOYMENT_TARGET)
        UILaunchScreen:
          UIColorName: ""
          UIImageName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSPhotoLibraryUsageDescription: "Snap Sieve needs access to analyze and identify duplicates. All processing is local."
        NSPhotoLibraryAddUsageDescription: "Snap Sieve needs permission to manage and delete photos."
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
          UISceneConfigurations: {}
    scheme:
      gatherCoverageData: true

  # ============================================
  # visionOS App Target
  # ============================================
  SnapSieveVision:
    type: application
    platform: visionOS
    sources:
      # visionOS-specific sources
      - path: SnapSieveVision
      # Shared Core sources
      - path: PhotoCleaner/Core/Algorithms
        group: Shared/Core/Algorithms
      - path: PhotoCleaner/Core/Models
        group: Shared/Core/Models
      - path: PhotoCleaner/Core/ML
        group: Shared/Core/ML
      - path: PhotoCleaner/Core/Utilities
        group: Shared/Core/Utilities
      # Shared services
      - path: PhotoCleaner/Core/Services/ImageAnalysisService.swift
        group: Shared/Core/Services
      - path: PhotoCleaner/Core/Services/DuplicateDetectionService.swift
        group: Shared/Core/Services
      - path: PhotoCleaner/Core/Services/SimilarityGroupingService.swift
        group: Shared/Core/Services
      - path: PhotoCleaner/Core/Services/QualityAssessmentService.swift
        group: Shared/Core/Services
      - path: PhotoCleaner/Core/Services/BatchProcessingService.swift
        group: Shared/Core/Services
      - path: PhotoCleaner/Core/Services/CLIPEmbeddingService.swift
        group: Shared/Core/Services
      # Shared Data layer
      - path: PhotoCleaner/Data
        group: Shared/Data
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.marlowsousa.snapsieve.vision
        INFOPLIST_FILE: SnapSieveVision/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SUPPORTED_PLATFORMS: xros
        XROS_DEPLOYMENT_TARGET: "1.0"
        LD_RUNPATH_SEARCH_PATHS:
          - "@executable_path/Frameworks"
    info:
      path: SnapSieveVision/Info.plist
      properties:
        CFBundleName: Snap Sieve
        CFBundleDisplayName: Snap Sieve
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        MinimumOSVersion: $(XROS_DEPLOYMENT_TARGET)
        UILaunchScreen:
          UIColorName: ""
          UIImageName: ""
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
          UIApplicationPreferredDefaultSceneSessionRole: UIWindowSceneSessionRoleApplication
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).AppDelegate
            UIWindowSceneSessionRoleImmersiveSpaceApplication:
              - UISceneConfigurationName: Immersive Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).ImmersiveDelegate
        NSPhotoLibraryUsageDescription: "Snap Sieve needs access to analyze and identify duplicates. All processing is local."
        NSPhotoLibraryAddUsageDescription: "Snap Sieve needs permission to manage and delete photos."
    scheme:
      gatherCoverageData: true

schemes:
  SnapSieve:
    build:
      targets:
        SnapSieve: all
        SnapSieveTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - SnapSieveTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  SnapSieveiOS:
    build:
      targets:
        SnapSieveiOS: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  SnapSieveVision:
    build:
      targets:
        SnapSieveVision: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
